Stage1
FadeiKholyavo/jet-start pull request #1
Opened 2021-04-23 00:06 UTC by FadeiKholyavo

2021-04-23 06:53 UTC, VeraOrekh requested changes

2021-04-23 06:53 UTC, VeraOrekh commented on sources/myapp.js
>  			start: "/top/start"
Нужно поменять стартовый урл, у тебя нет файла start.js в папке views, поэтому при открытии приложения появляется ошибка

2021-04-23 06:53 UTC, VeraOrekh commented on sources/myapp.js
> +			app.show("/top");
Если перейти по данному урлу, то вьюшка top не растягивается на весь экран.
Поэтому либо добавь спейсер, либо укажи урл top/contacts, чтобы автоматически выбиралась первая вкладка

2021-04-23 06:53 UTC, VeraOrekh commented on sources/models/activities-type.js
> +			obj.value = obj.Value;
Предполагаю, что где-то не был задан темплейт, поэтому тебе пришлось добавить свойство value.
Лучше задать темплейт там, где он нужен

2021-04-23 06:53 UTC, VeraOrekh commented on sources/models/contacts.js
> +			obj.value = `${obj.FirstName} ${obj.LastName}`;
Тоже лучше будет использовать темплейт

2021-04-23 06:53 UTC, VeraOrekh commented on sources/views/activities.js
> +				{id: "DueDate", header: [{text: "Due date"}, {content: "dateRangeFilter", inputConfig: {format: webix.Date.dateToStr("%j %F %Y")}}], sort: "date", format: webix.Date.dateToStr("%j %F %Y"), width:
Если есть большие конфиги, то лучше писать каждое новое свойство на новой строке, т.к. такие длинные конфиги очень сложно читать

2021-04-23 06:53 UTC, VeraOrekh commented on sources/views/common-popup.js
> +					options: activitiesType
Чтобы задать темплейт для richselect можно сделать так:
```
{
    view: "richselect",
    ...
    options: {
        body: {
            data: activitiesType,
            template: "#Value#"
        }
    }
}
```

2021-04-23 06:53 UTC, VeraOrekh commented on sources/views/common-popup.js
> +									label: this.settings[1] || this.settings[0],
Здесь лушче добавить проверку, что this.settings это массив
Или в конструкторе сразу задать свойства, имена которых будут отображать суть, что за settings[0] и settings[1]

2021-04-23 06:53 UTC, VeraOrekh commented on sources/views/common-popup.js
> +				const time = webix.i18n.dateFormatDate(formItem.Time);
Дата и время являются необязательными полями для заполнения при создании activity. Поэтому перед тем, как передать данное значение в функцию, следует проверить, а есть ли значение. Если дата или время незаполнены, то webix.i18n.dateFormatDate вернёт пустую строку. Поэтому при вызове date.getFullYear() вылетит ошибка в консоль

2021-04-23 06:53 UTC, VeraOrekh commented on sources/views/top.js
> +			template: "<span class=\"fas #icon#\"></span> <span class=\"item\">#value#</span> ",
Можно использовать синтаксис es6(`), чтобы не экранировать двойные кавычки

2021-04-23 06:53 UTC, VeraOrekh commented on sources/views/contacts-template.js
> +							return `<div class="contacts-template">
Т.к. темплейт очень большой, то можно создать переменные, которые будут содержать отдельные части темплейта. Например, лист с информацией об юзере, первая, вторая строка. Так код будет более читабельным

2021-04-23 11:30 UTC, VeraOrekh requested changes

2021-04-23 11:30 UTC, VeraOrekh commented on sources/views/activities.js
> +						return `${contact.FirstName} ${contact.LastName}`;
Добавь проверку на существование contact

2021-04-23 11:30 UTC, VeraOrekh commented on sources/views/contacts-template.js
> +                                                    <li><span class="fas fa-at"></span>${(obj && obj.Email) || "-"}</li>
Поправь табуляцию

2021-04-23 12:00 UTC, VeraOrekh approved these changes

2021-04-23 18:59 UTC, HelgaListopad requested changes

2021-04-23 18:59 UTC, HelgaListopad commented on sources/models/activities.js
> +			const parse = webix.Date.dateToStr("%Y-%m-%d %H:%i");
парсер было бы красивее вынести как константу рядом с activities. Каждый раз вызывать его по-новой довольно избыточно, так как

- $init/$save вызываются для каждой отдельной записи
- dateToStr возвращает метод форматирования, который можно подготовить один раз заранее.

2021-04-23 18:59 UTC, HelgaListopad commented on sources/views/activities.js
> +					this.ui(new CommonPopup(this.app, "", ["Edit", "Save"], activities, item)).showWindow();
Каждый раз по клику на кнопку создаётся новый экземпляр окна.
Когда в нём нажимаешь Save/Add или Cancel, оно не рарзушается, а прячется - как результат, на этой странице, пока с неё не перейти (`this.ui` всё-таки привязывает жизнь окна к parent-классу), плодится масса спрятанных неиспользуемых окон. 

Это следует исправить на переиспользование одного и того же окна.

- на `init` твоей вьюшки activities создаёшь один попап
```
this.popup = this.ui( ... );
```
- когда нужно, вызываешь от него `showWindow`, передавая туда нужные параметры для того, чтобы определить, edit это или add (`id` достаточно);
- в зависимости от этого параметра в окне меняется: 
 -- текст в двух местах, 
 -- и для сохранения данных на коллекции вызывается `add`/`updateItem` соответственно;
- когда окно пора спрятать, чистится форма, чистится валидация, окно прячется через `hide`.

2021-04-23 18:59 UTC, HelgaListopad commented on sources/views/activities.js
> +				this.ui(new CommonPopup(this.app, "", ["Add"], activities)).showWindow();
См. комментарий выше про переиспользование окон

2021-04-23 18:59 UTC, HelgaListopad commented on sources/views/activities.js
> +			this.activitiesDatatatble.sync(activities);
`sync` можно использовать без промисов - коллекция и так передаст таблице анные, конда они придут.
К тому же, нет смысла ждать данные из трёх источников, если здесь используется только один.

2021-04-23 18:59 UTC, HelgaListopad commented on sources/views/common-popup.js
> +				this.getRoot().hide();
Я выше оставила комментарий, как переиспользовать окно - напоминаю здесь, что при закрытии такого окна понадобится 
- чистить значения
- чистить валидацию
- уже потом прятать окно

(и по Cancel тоже - поэтому всё можно вывести в отдельный метод)

2021-04-23 18:59 UTC, HelgaListopad commented on sources/views/contacts-template.js
> +			const id = url[0].params.user;
Лучше не обращаться напрямую к урлу и использовать [getParam](https://webix.gitbook.io/webix-jet/api/jetview-api/jetview-methods#this-getparam)

2021-04-23 18:59 UTC, HelgaListopad commented on sources/views/contacts.js
> +			const id = url[0].params.user;
И снова `getParam`

2021-04-23 18:59 UTC, HelgaListopad commented on sources/views/top.js
> +			]
template ожидает в качестве данных один data item, то есть достаточно объекта `{page: ""}`

2021-04-23 18:59 UTC, HelgaListopad commented on sources/views/top.js
> +		this.header.data.page = (url[1] && url[1].page) || "CRM";
Вместо url тут вполне удобно было бы использовать value из выбранной опции меню.
```
this.header.setValues({ page: /*...*/ }) // .refresh() will be unnecessary
```
В целом, напрямую разбирать URL не очень хорошо, так как это довольно сложная меняюўаяся структура. 
Для подобных задач есть подходящие методы API (`get/setParam`) и, как здесь, альтернативный источник данных.

2021-04-26 14:09 UTC, HelgaListopad approved these changes

2021-04-26 14:11 UTC, merged