Stage3
FadeiKholyavo/jet-start pull request #3
Opened 2021-05-04 22:56 UTC by FadeiKholyavo

2021-05-05 07:18 UTC, VeraOrekh requested changes

2021-05-05 07:18 UTC, VeraOrekh commented on sources/views/settings/settings.js
> +		const value = this.getRoot().queryView({view: "segmented"}).getValue();
Добавь геттер для segmented

2021-05-05 07:18 UTC, VeraOrekh commented on sources/views/settings/settings.js
> +						{
Лучше не делать один segmented на полстраницы

2021-05-05 07:18 UTC, VeraOrekh commented on sources/views/settings/settings-datatable.js
> +				{height: 11}
А зачем тут высота выставлена?

2021-05-05 07:18 UTC, VeraOrekh commented on sources/views/contacts/contacts.js
> +			this.app.callEvent("ContactsTemplate:onAfterContactSelect", [true]);
Если данный ивент нужно вызывать после каждого селекта, то лучше добавить его вызов на onAfterSelect листа

2021-05-05 07:18 UTC, VeraOrekh commented on sources/views/activities/activities-filters.js
> +		this.on(this.app, "ActivitiesFilters:getDatatable", (datatable) => {
Ивенты обычно не называют getDatatable, больше похоже на геттер

2021-05-05 07:18 UTC, VeraOrekh commented on sources/views/activities/activities-datatable.js
> +			this.activitiesDatatatble.setState({filter: {undefined: "All"}});
А почему здесь undefined?

2021-05-05 10:19 UTC, VeraOrekh requested changes

2021-05-05 10:19 UTC, VeraOrekh commented on sources/views/contacts/contacts-form.js
>  					label: "Email",
Забыл добавить локализацию

2021-05-05 10:33 UTC, VeraOrekh approved these changes

2021-05-05 16:28 UTC, HelgaListopad requested changes
Всё в целом хорошо, но нужно выровнять иконки во всех списках, где рядом с ними название (я оставила один комментарий по этому поводу для activities datatable, но потом заметила, что это общая проблема)

Сравни вариант с выравниванием
![image](https://user-images.githubusercontent.com/7587383/117171221-5d4d8c00-add3-11eb-864f-0e6724903c90.png)
И текущий
![image](https://user-images.githubusercontent.com/7587383/117171349-78b89700-add3-11eb-8edd-9866a3614d06.png)

2021-05-05 16:28 UTC, HelgaListopad commented on sources/views/activities/activities-datatable.js
> +						return (activityTypeValue && `${activityTypeValue}   <span class="fas fa-${icon}"></span>`) || "Type";
Иконки стоит выровнять по левому (перед названием) или правому краю ячейки, иначе выглядит тяжеловато дл глаз

2021-05-06 08:13 UTC, HelgaListopad approved these changes

2021-05-06 09:32 UTC, merged